export type Lang="ru"|"en"; export type Scenario="realEstate"|"investors"|"companies";
export type Result={id:number;title:string;location:string;area:string;price:string;match:number;evidence:string;status:"Verified"|"Reviewed"|"Manual review";source:string;url:string;why:string};
export type Source={name:string;category:string;health:"Healthy"|"Warning";quality:number;method:string;lastChecked:string;status:"Active"|"Review";url:string;domain:string;description:string};
export const sourceRegistry:Source[]=[
{name:"idealista",category:"Real Estate",health:"Healthy",quality:94,method:"Public web / browser",lastChecked:"2 min ago",status:"Active",url:"https://www.idealista.com/venta-terrenos/madrid-madrid/",domain:"idealista.com",description:"Madrid land listings and filters."},
{name:"Comunidad de Madrid — Visor SIT",category:"Government",health:"Healthy",quality:97,method:"Public web / map",lastChecked:"12 min ago",status:"Active",url:"https://www.comunidad.madrid/medio-ambiente/sistema-informacion-territorial-visor-sit",domain:"comunidad.madrid",description:"Urban planning information for Madrid municipalities."},
{name:"Sede Electrónica del Catastro",category:"Cadastre",health:"Healthy",quality:98,method:"Public portal",lastChecked:"18 min ago",status:"Active",url:"https://www.sedecatastro.gob.es/",domain:"sedecatastro.gob.es",description:"Cadastral references and parcel information."},
{name:"Portal del Suelo 4.0",category:"Public land",health:"Healthy",quality:96,method:"Web / CSV / JSON",lastChecked:"24 min ago",status:"Active",url:"https://www.comunidad.madrid/inversion-empresa/portal-suelo-40",domain:"comunidad.madrid",description:"Public land parcels, use and planning parameters."},
{name:"Geoportal Comunidad de Madrid",category:"Geospatial",health:"Healthy",quality:95,method:"Web / geodata",lastChecked:"32 min ago",status:"Active",url:"https://www.comunidad.madrid/geoportal",domain:"comunidad.madrid",description:"Official geographic data and visualisation services."},
{name:"CartoMadrid",category:"Geospatial",health:"Healthy",quality:93,method:"Web / map",lastChecked:"41 min ago",status:"Active",url:"https://www.comunidad.madrid/medio-ambiente/cartografia-topografica-tematica",domain:"comunidad.madrid",description:"Topography, aerial imagery and planning layers."},
{name:"Demo hard source",category:"Real Estate",health:"Warning",quality:64,method:"Browser",lastChecked:"1 h ago",status:"Review",url:"https://example.com/",domain:"example.com",description:"Demo-only source to show warning/manual-review UX."}
];
export const scenarios={
realEstate:{label:"Real Estate",labelRu:"Недвижимость",query:"Найди земельные участки в Мадриде площадью от 10 000 м², подходящие под мои критерии.",queryEn:"Find land parcels in Madrid above 10,000 m² suitable for my criteria.",sourcesFound:520,sourcesChecked:347,qualified:86,duplicates:510,evidence:91,remaining:"~8 min",categories:[["Real Estate Portals",126,94,"strong"],["Local Agencies",84,88,"strong"],["Municipal / Public",73,82,"medium"],["Bank & Auctions",54,76,"medium"],["Forums / Communities",61,58,"weak"],["Other Sources",89,64,"medium"]]},
investors:{label:"Investors",labelRu:"Инвесторы",query:"Найди потенциальных инвесторов в Амстердаме для технологического проекта X.",queryEn:"Find potential investors in Amsterdam for technology project X.",sourcesFound:412,sourcesChecked:286,qualified:58,duplicates:304,evidence:88,remaining:"~6 min",categories:[["VC Funds",76,94,"strong"],["Angel Networks",63,89,"strong"],["Family Offices",51,81,"medium"],["Accelerators",44,79,"medium"],["Conferences",72,70,"medium"],["Professional Networks",106,55,"weak"]]},
companies:{label:"Companies",labelRu:"Компании",query:"Найди производителей промышленной упаковки в Китае с экспортом в ЕС.",queryEn:"Find industrial packaging manufacturers in China exporting to the EU.",sourcesFound:684,sourcesChecked:455,qualified:112,duplicates:618,evidence:90,remaining:"~11 min",categories:[["Manufacturer Directories",168,93,"strong"],["Company Websites",142,92,"strong"],["Trade Portals",124,84,"medium"],["Export Registries",86,79,"medium"],["Industry Associations",72,73,"medium"],["Communities",92,57,"weak"]]}
} as const;
export const resultsByScenario:Record<Scenario,Result[]>= {
realEstate:[
{id:1,title:"Finca Madrid Norte",location:"Madrid, ES",area:"12,800 m²",price:"€1.84M",match:96,evidence:"Planning / listing evidence",status:"Verified",source:"idealista",url:"https://www.idealista.com/venta-terrenos/madrid-madrid/",why:"Area threshold met; location and land type match the demo criteria."},
{id:2,title:"Parcela Industrial Sur",location:"Getafe, ES",area:"18,420 m²",price:"€2.12M",match:93,evidence:"Listing + location evidence",status:"Verified",source:"idealista",url:"https://www.idealista.com/venta-terrenos/madrid-madrid/",why:"Large parcel within Madrid metro area; source link retained."},
{id:3,title:"Urban Expansion Plot",location:"Alcalá, ES",area:"10,250 m²",price:"€1.31M",match:91,evidence:"Planning map evidence",status:"Reviewed",source:"Comunidad de Madrid — Visor SIT",url:"https://www.comunidad.madrid/medio-ambiente/sistema-informacion-territorial-visor-sit",why:"Planning source can be used to validate the parcel's planning context."},
{id:4,title:"Development Opportunity",location:"Móstoles, ES",area:"24,000 m²",price:"€3.42M",match:88,evidence:"Listing evidence",status:"Reviewed",source:"idealista",url:"https://www.idealista.com/venta-terrenos/madrid-madrid/",why:"Strong area fit; planning suitability requires deeper verification."}
],
investors:[
{id:11,title:"Amsterdam Growth Fund",location:"Amsterdam, NL",area:"B2B / SaaS",price:"Series A–B",match:94,evidence:"Public investment thesis",status:"Verified",source:"Public fund site",url:"https://example.com/",why:"Thesis and geography match the demo investment profile."},
{id:12,title:"Climate Tech Angel Network",location:"Amsterdam, NL",area:"Climate / Deeptech",price:"€250k–€1M",match:92,evidence:"Network profile",status:"Verified",source:"Public network",url:"https://example.com/",why:"Relevant sector and ticket size shown in public material."},
{id:13,title:"Family Office — NL",location:"Amsterdam, NL",area:"Technology",price:"Private",match:84,evidence:"Public portfolio references",status:"Manual review",source:"Public sources",url:"https://example.com/",why:"Potential fit, but mandate requires manual verification."}
],
companies:[
{id:21,title:"Ningbo Industrial Packaging",location:"Zhejiang, CN",area:"Industrial packaging",price:"EU export",match:95,evidence:"Company profile + export evidence",status:"Verified",source:"Public company source",url:"https://example.com/",why:"Product category and EU export signals match the demo criteria."},
{id:22,title:"Guangdong Flexible Pack Co.",location:"Guangdong, CN",area:"Flexible packaging",price:"EU / UK",match:90,evidence:"Trade profile",status:"Reviewed",source:"Trade portal",url:"https://example.com/",why:"Strong product match; final export verification pending."}
]};
