export type Lang = "ru" | "en";
export type Scenario = "realEstate" | "investors" | "companies";

export type NavKey = "research" | "tasks" | "sources" | "results" | "settings";

export type ResultStatus = "Verified" | "Reviewed" | "Manual review";

export type Result = {
  id: number;
  title: string;
  organization?: string;
  specialization?: string;
  geography?: string;
  contact?: string;
  investmentType?: string;
  stage?: string;
  ticket?: string;
  location: string;
  area: string;
  price: string;
  match: number;
  evidence: string;
  status: ResultStatus;
  source: string;
  url: string;
  why: string;
  sourceType?: string;
  sourceDomain?: string;
  evidenceQuote?: string;
  retrievedAt?: string;
  freshnessDays?: number;
  confidence?: number;
  independentVerification?: boolean;
  qualityGate?: {
    gate: "PASS" | "REVIEW" | "FAIL";
    passed: number;
    total: number;
    checks: Record<string, boolean>;
    independentVerification: boolean;
    note: string;
  };
};

export type SourceHealth = "Healthy" | "Warning" | "Review";

export type Source = {
  name: string;
  category: string;
  health: SourceHealth;
  quality: number;
  method: string;
  lastChecked: string;
  status: "Active" | "Review";
  access: string;
  dataAvailable: string;
  rateLimits: string;
  robotsTerms: string;
  cost: string;
  decision: "Keep" | "Optional" | "Manual" | "Exclude";
  url: string;
  domain: string;
  description: string;
};

export type Task = {
  id: string;
  title: string;
  status: "Running" | "Completed" | "Paused";
  date: string;
  duration: string;
  results: number;
  scenario: Scenario;
};

export const sourceRegistry: Source[] = [
  {
    name: "idealista — Madrid land",
    category: "Property portal",
    health: "Healthy",
    quality: 94,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Listings, price, area, type",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.idealista.com/venta-terrenos/madrid-madrid/",
    domain: "idealista.com",
    description: "Madrid land listings with filters for size and land type.",
  },
  {
    name: "idealista — urban land",
    category: "Property portal",
    health: "Healthy",
    quality: 94,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Urban plots, price, area",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.idealista.com/venta-terrenos/madrid-madrid/con-terrenos-urbanos/",
    domain: "idealista.com",
    description: "Urban land subset.",
  },
  {
    name: "idealista — developable land",
    category: "Property portal",
    health: "Healthy",
    quality: 94,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Developable plots, price, area",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.idealista.com/venta-terrenos/madrid-madrid/con-terrenos-urbanizables/",
    domain: "idealista.com",
    description: "Developable land subset.",
  },
  {
    name: "idealista — last month",
    category: "Fresh listings",
    health: "Healthy",
    quality: 91,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Recent listings, price, area",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.idealista.com/venta-terrenos/madrid-madrid/con-publicado_ultimo-mes/",
    domain: "idealista.com",
    description: "Recent-publication subset.",
  },
  {
    name: "Habitaclia — Madrid land",
    category: "Property portal",
    health: "Healthy",
    quality: 89,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Listings, price, area",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.habitaclia.com/comprar/terrenos_y_solares/madrid-provincia/madrid-capital/s/3",
    domain: "habitaclia.com",
    description: "Madrid capital land and solar listings.",
  },
  {
    name: "Pisos.com — developable Madrid",
    category: "Property portal",
    health: "Healthy",
    quality: 89,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Listings, price, area, buildability",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.pisos.com/venta/terrenos-madrid/edificable/",
    domain: "pisos.com",
    description: "Edificable land route.",
  },
  {
    name: "Pisos.com — Madrid capital",
    category: "Property portal",
    health: "Healthy",
    quality: 87,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Listings, filters, map",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.pisos.com/venta/terrenos-madrid_capital/",
    domain: "pisos.com",
    description: "Madrid capital land route.",
  },
  {
    name: "Pisos.com — Madrid North",
    category: "Property portal",
    health: "Healthy",
    quality: 87,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Regional listings",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.pisos.com/venta/terrenos-madrid_norte/",
    domain: "pisos.com",
    description: "Madrid North route.",
  },
  {
    name: "Pisos.com — Barajas",
    category: "Property portal",
    health: "Healthy",
    quality: 88,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Large plots, price, area",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.pisos.com/venta/terrenos-madrid_capital_barajas/",
    domain: "pisos.com",
    description: "Barajas land route.",
  },
  {
    name: "Fotocasa — Madrid land",
    category: "Property portal",
    health: "Healthy",
    quality: 89,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Listings, price, area",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.fotocasa.es/es/comprar/terrenos/madrid-capital/todas-las-zonas/l",
    domain: "fotocasa.es",
    description: "Madrid capital land listings.",
  },
  {
    name: "Yaencontre — Madrid land",
    category: "Property portal",
    health: "Healthy",
    quality: 88,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Public",
    dataAvailable: "Listings, municipality, price, area",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.yaencontre.com/venta/terrenos/madrid",
    domain: "yaencontre.com",
    description: "Madrid province land discovery.",
  },
  {
    name: "Yaencontre — private owners",
    category: "Property portal / private",
    health: "Warning",
    quality: 82,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Review",
    access: "Public",
    dataAvailable: "Private listings, price, area",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Optional",
    url: "https://www.yaencontre.com/venta/terrenos/madrid-provincia/e-particulares",
    domain: "yaencontre.com",
    description: "Private-owner subset.",
  },
  {
    name: "Milanuncios — Madrid",
    category: "Classifieds",
    health: "Warning",
    quality: 78,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Review",
    access: "Public",
    dataAvailable: "Listings, price, area, seller text",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Optional",
    url: "https://www.milanuncios.com/terrenos-en-madrid-madrid/",
    domain: "milanuncios.com",
    description: "Large classifieds pool; noisy data expected.",
  },
  {
    name: "Milanuncios — Madrid province",
    category: "Classifieds",
    health: "Warning",
    quality: 77,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Review",
    access: "Public",
    dataAvailable: "Listings, area, seller text",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Optional",
    url: "https://www.milanuncios.com/terrenos-en-madrid/",
    domain: "milanuncios.com",
    description: "Province-wide classifieds.",
  },
  {
    name: "Milanuncios — rural parcels",
    category: "Classifieds",
    health: "Warning",
    quality: 75,
    method: "Browser",
    lastChecked: "Stage 1 baseline",
    status: "Review",
    access: "Public",
    dataAvailable: "Rural parcels, area, price",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Optional",
    url: "https://www.milanuncios.com/parcelas-en-madrid/terreno.htm",
    domain: "milanuncios.com",
    description: "Rural parcel subset.",
  },
  {
    name: "Comunidad de Madrid — Portal del Suelo 4.0",
    category: "Public land",
    health: "Healthy",
    quality: 98,
    method: "Web / JSON / CSV",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Use, area, buildability, class, regime, location",
    rateLimits: "Public dataset",
    robotsTerms: "Public terms",
    cost: "€0",
    decision: "Keep",
    url: "https://www.comunidad.madrid/inversion-empresa/portal-suelo-40",
    domain: "comunidad.madrid",
    description: "Official public land portal.",
  },
  {
    name: "Comunidad de Madrid — parcelas CKAN",
    category: "Open data",
    health: "Healthy",
    quality: 99,
    method: "JSON / CSV",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Parcel records and geographic link",
    rateLimits: "Dataset schedule",
    robotsTerms: "Open data terms",
    cost: "€0",
    decision: "Keep",
    url: "https://datos.comunidad.madrid/dataset/parcelas_portal_suelo",
    domain: "datos.comunidad.madrid",
    description: "Machine-readable land dataset.",
  },
  {
    name: "Comunidad de Madrid — soil heritage",
    category: "Government",
    health: "Healthy",
    quality: 96,
    method: "Web / document",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Public land inventory",
    rateLimits: "Annual",
    robotsTerms: "Public",
    cost: "€0",
    decision: "Keep",
    url: "https://www.comunidad.madrid/transparencia/patrimonio-suelo",
    domain: "comunidad.madrid",
    description: "Public land inventory and updates.",
  },
  {
    name: "Comunidad de Madrid — GeoPortal",
    category: "Geospatial",
    health: "Healthy",
    quality: 97,
    method: "Map / services",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Geodata, map layers, downloads",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.comunidad.madrid/geoportal",
    domain: "comunidad.madrid",
    description: "Official geographic information portal.",
  },
  {
    name: "Comunidad de Madrid — Cartography",
    category: "Geospatial",
    health: "Healthy",
    quality: 96,
    method: "Map / downloads",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Topographic and thematic data",
    rateLimits: "Unknown",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://www.comunidad.madrid/medio-ambiente/cartografia-topografica-tematica",
    domain: "comunidad.madrid",
    description: "Topographic/thematic cartography.",
  },
  {
    name: "Comunidad de Madrid — IDEM catalog",
    category: "Geospatial catalog",
    health: "Healthy",
    quality: 95,
    method: "Catalog / services",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Metadata, datasets, services",
    rateLimits: "Catalog dependent",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://idem.comunidad.madrid/catalogocartografia/catalogocartografia/search",
    domain: "idem.comunidad.madrid",
    description: "Catalog of regional geographic resources.",
  },
  {
    name: "IDEM — Parcelas Portal Suelo dataset",
    category: "Geospatial dataset",
    health: "Healthy",
    quality: 97,
    method: "Dataset / service",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Land-use parcel data",
    rateLimits: "Continuous",
    robotsTerms: "Review",
    cost: "€0 public",
    decision: "Keep",
    url: "https://idem.comunidad.madrid/catalogocartografia/srv/resources/datasets/spacm_parcelaspsuelo",
    domain: "idem.comunidad.madrid",
    description: "Official parcel dataset resource.",
  },
  {
    name: "Madrid Open Data — urbanism",
    category: "Open data",
    health: "Healthy",
    quality: 97,
    method: "CSV / JSON / GEO",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Urbanism and infrastructure datasets",
    rateLimits: "Dataset specific",
    robotsTerms: "CC / portal terms",
    cost: "€0",
    decision: "Keep",
    url: "https://datos.madrid.es/group/urbanismo-infraestructuras",
    domain: "datos.madrid.es",
    description: "Large urbanism dataset group.",
  },
  {
    name: "Madrid — land use / planning",
    category: "Urban planning",
    health: "Healthy",
    quality: 98,
    method: "Map service",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Land-use destination by parcel",
    rateLimits: "Dataset specific",
    robotsTerms: "CC BY 4.0 / portal terms",
    cost: "€0",
    decision: "Keep",
    url: "https://datos.madrid.es/dataset/300744-0-usos-suelo-urbanismo",
    domain: "datos.madrid.es",
    description: "Planning map for land destination.",
  },
  {
    name: "Madrid Geoportal — VEDA Jan 2026",
    category: "Buildability",
    health: "Healthy",
    quality: 97,
    method: "Map service",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Available buildability by use",
    rateLimits: "Dataset specific",
    robotsTerms: "Portal terms",
    cost: "€0",
    decision: "Keep",
    url: "https://geoportal.madrid.es/IDEAM_WBGEOPORTAL/dataset.iam?id=85497849-dgpe-eu-0001-87b3-fc8b28826a92",
    domain: "geoportal.madrid.es",
    description: "January 2026 buildability dataset.",
  },
  {
    name: "Madrid Geoportal — VEDA Jul 2025",
    category: "Buildability",
    health: "Healthy",
    quality: 95,
    method: "WMS / REST",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Buildable capacity and parcels",
    rateLimits: "Dataset specific",
    robotsTerms: "Portal terms",
    cost: "€0",
    decision: "Keep",
    url: "https://geoportal.madrid.es/IDEAM_WBGEOPORTAL/dataset.iam?id=85497849-dgpe-eu-0001-87b3-fc8b28826a91",
    domain: "geoportal.madrid.es",
    description: "Earlier VEDA snapshot for comparison.",
  },
  {
    name: "Madrid Sede — public soil",
    category: "Municipal public land",
    health: "Healthy",
    quality: 97,
    method: "Web / portal",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Public municipal plots",
    rateLimits: "Public portal",
    robotsTerms: "Portal terms",
    cost: "€0",
    decision: "Keep",
    url: "https://sede.madrid.es/portal/site/tramites/menuitem.1f3361415fda829be152e15284f1a5a0/?vgnextchannel=ba71071be68d1810VgnVCM2000001f4a900aRCRD&vgnextoid=630daf2d7aa36810VgnVCM1000001d4a900aRCRD",
    domain: "sede.madrid.es",
    description: "Municipal public land information.",
  },
  {
    name: "Sede Electrónica del Catastro",
    category: "Cadastre",
    health: "Healthy",
    quality: 99,
    method: "Web / map",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Cadastral map and non-protected data",
    rateLimits: "Service limits",
    robotsTerms: "Terms / policy",
    cost: "€0",
    decision: "Keep",
    url: "https://www.sedecatastro.gob.es/",
    domain: "sedecatastro.gob.es",
    description: "Official cadastral access.",
  },
  {
    name: "Catastro — public lookup help",
    category: "Cadastre",
    health: "Healthy",
    quality: 99,
    method: "Web",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Parcel reference / location lookup",
    rateLimits: "Service limits",
    robotsTerms: "Terms / policy",
    cost: "€0",
    decision: "Keep",
    url: "https://www.catastro.hacienda.gob.es/ayuda/ayuda_cl.htm",
    domain: "catastro.hacienda.gob.es",
    description: "Public data lookup rules and fields.",
  },
  {
    name: "PLACSP — Madrid land disposal",
    category: "Public procurement / land sale",
    health: "Healthy",
    quality: 97,
    method: "Tender documents",
    lastChecked: "Stage 1 baseline",
    status: "Active",
    access: "Open",
    dataAvailable: "Parcel lots, price, urban conditions",
    rateLimits: "Portal dependent",
    robotsTerms: "Public procurement terms",
    cost: "€0",
    decision: "Keep",
    url: "https://contrataciondelestado.es/",
    domain: "contrataciondelestado.es",
    description: "Public tenders and municipal land disposal.",
  },
];

export const scenarios = {
  realEstate: {
    label: "Real Estate",
    labelRu: "Недвижимость",
    query:
      "Найди земельные участки в Мадриде площадью от 10 000 м², подходящие под мои критерии.",
    queryEn:
      "Find land parcels in Madrid above 10,000 m² suitable for my criteria.",
    sourcesFound: 520,
    sourcesChecked: 347,
    qualified: 86,
    duplicates: 510,
    evidence: 91,
    remaining: "~8 min",
    categories: [
      ["Real Estate Portals", 126, 94, "strong"],
      ["Local Agencies", 84, 88, "strong"],
      ["Municipal / Public", 73, 82, "medium"],
      ["Bank & Auctions", 54, 76, "medium"],
      ["Forums / Communities", 61, 58, "weak"],
      ["Other Sources", 89, 64, "medium"],
    ],
  },
  investors: {
    label: "Investors",
    labelRu: "Инвесторы",
    query:
      "Найди потенциальных инвесторов в Амстердаме для технологического проекта X.",
    queryEn:
      "Find potential investors in Amsterdam for technology project X.",
    sourcesFound: 412,
    sourcesChecked: 286,
    qualified: 58,
    duplicates: 304,
    evidence: 88,
    remaining: "~6 min",
    categories: [
      ["VC Funds", 76, 94, "strong"],
      ["Angel Networks", 63, 89, "strong"],
      ["Family Offices", 51, 81, "medium"],
      ["Accelerators", 44, 79, "medium"],
      ["Conferences", 72, 70, "medium"],
      ["Professional Networks", 106, 55, "weak"],
    ],
  },
  companies: {
    label: "Companies",
    labelRu: "Компании",
    query:
      "Найди производителей промышленной упаковки в Китае с экспортом в ЕС.",
    queryEn:
      "Find industrial packaging manufacturers in China exporting to the EU.",
    sourcesFound: 684,
    sourcesChecked: 455,
    qualified: 112,
    duplicates: 618,
    evidence: 90,
    remaining: "~11 min",
    categories: [
      ["Manufacturer Directories", 168, 93, "strong"],
      ["Company Websites", 142, 92, "strong"],
      ["Trade Portals", 124, 84, "medium"],
      ["Export Registries", 86, 79, "medium"],
      ["Industry Associations", 72, 73, "medium"],
      ["Communities", 92, 57, "weak"],
    ],
  },
} as const;

export const resultsByScenario: Record<Scenario, Result[]> = {
  realEstate: [
    {
      id: 1,
      title: "Finca Madrid Norte",
      location: "Madrid, ES",
      area: "12,800 m²",
      price: "€1.84M",
      match: 96,
      evidence: "Listing / planning evidence",
      status: "Verified",
      source: "idealista",
      url: "https://www.idealista.com/venta-terrenos/madrid-madrid/",
      why: "Illustrative demo result: the target area threshold and Madrid geography are represented in the mock result.",
    },
    {
      id: 2,
      title: "Parcela Industrial Sur",
      location: "Getafe, ES",
      area: "18,420 m²",
      price: "€2.12M",
      match: 93,
      evidence: "Listing + location evidence",
      status: "Verified",
      source: "idealista",
      url: "https://www.idealista.com/venta-terrenos/madrid-madrid/",
      why: "Illustrative demo result: large parcel within the Madrid metro area.",
    },
    {
      id: 3,
      title: "Urban Expansion Plot",
      location: "Alcalá de Henares, ES",
      area: "10,250 m²",
      price: "€1.31M",
      match: 91,
      evidence: "Planning map evidence",
      status: "Reviewed",
      source: "Comunidad de Madrid — Visor SIT",
      url: "https://www.comunidad.madrid/medio-ambiente/sistema-informacion-territorial-visor-sit",
      why: "Illustrative demo result: planning context is represented as a second-stage verification source.",
    },
    {
      id: 4,
      title: "Development Opportunity",
      location: "Móstoles, ES",
      area: "24,000 m²",
      price: "€3.42M",
      match: 88,
      evidence: "Listing evidence",
      status: "Reviewed",
      source: "Portal del Suelo 4.0",
      url: "https://www.comunidad.madrid/inversion-empresa/portal-suelo-40",
      why: "Illustrative demo result: public-land source is shown as a verification/discovery layer.",
    },
  ],
  investors: [
    {
      id: 11,
      title: "Amsterdam Growth Ecosystem",
      location: "Amsterdam, NL",
      area: "B2B / SaaS",
      price: "Series A–B",
      match: 94,
      evidence: "Public ecosystem source",
      status: "Verified",
      source: "Amsterdam Invest",
      url: "https://www.iamsterdam.com/en/business/invest",
      why: "Illustrative demo result linked to a real public Amsterdam investment ecosystem source.",
    },
    {
      id: 12,
      title: "Dutch Climate-Tech Network",
      location: "Amsterdam, NL",
      area: "Climate / Deeptech",
      price: "€250k–€1M",
      match: 91,
      evidence: "Public ecosystem source",
      status: "Reviewed",
      source: "Amsterdam Invest",
      url: "https://www.iamsterdam.com/en/business/invest",
      why: "Illustrative demo result for demonstrating an adaptive investor schema.",
    },
    {
      id: 13,
      title: "Technology Investment Lead",
      location: "Amsterdam, NL",
      area: "Technology",
      price: "Private",
      match: 84,
      evidence: "Public reference required",
      status: "Manual review",
      source: "Amsterdam Invest",
      url: "https://www.iamsterdam.com/en/business/invest",
      why: "Illustrative demo result intentionally flagged for human verification.",
    },
  ],
  companies: [
    {
      id: 21,
      title: "Ningbo Industrial Packaging",
      location: "Zhejiang, CN",
      area: "Industrial packaging",
      price: "EU export",
      match: 95,
      evidence: "Directory source",
      status: "Verified",
      source: "Global Sources",
      url: "https://www.globalsources.com/",
      why: "Illustrative demo result linked to a real B2B supplier discovery source.",
    },
    {
      id: 22,
      title: "Guangdong Flexible Pack Co.",
      location: "Guangdong, CN",
      area: "Flexible packaging",
      price: "EU / UK",
      match: 90,
      evidence: "Supplier directory",
      status: "Reviewed",
      source: "Global Sources",
      url: "https://www.globalsources.com/",
      why: "Illustrative demo result; export verification remains a second-stage step.",
    },
    {
      id: 23,
      title: "Industrial Packaging Supplier",
      location: "Foshan, CN",
      area: "B2B packaging",
      price: "OEM / private label",
      match: 86,
      evidence: "Marketplace source",
      status: "Manual review",
      source: "Alibaba",
      url: "https://www.alibaba.com/",
      why: "Illustrative demo result showing a marketplace source with manual validation state.",
    },
  ],
};

export const tasks: Task[] = [
  {
    id: "AURE-0427",
    title: "Madrid land discovery",
    status: "Running",
    date: "Today, 15:42",
    duration: "6m 24s",
    results: 86,
    scenario: "realEstate",
  },
  {
    id: "AURE-0424",
    title: "Amsterdam investor discovery",
    status: "Completed",
    date: "Today, 13:18",
    duration: "11m 08s",
    results: 58,
    scenario: "investors",
  },
  {
    id: "AURE-0419",
    title: "China packaging suppliers",
    status: "Paused",
    date: "Yesterday, 18:33",
    duration: "8m 42s",
    results: 112,
    scenario: "companies",
  },
];
